### ISSUE TITLE
The injector doesn't work if the deployment is in a different namespace

### ISSUE THREAD

**Issue by gamer22026** [hooksie1/cmsnr#4]
Seems to only work if the deployment to be injected is in the same namespace as the mutating webhook. Otherwise repeatedly  throws the error:
```
time="2022-02-07T21:22:59Z" level=info msg="Injecting sidecar for "
time="2022-02-07T21:22:59Z" level=info msg="no service account defined, adding cmsnr account"

```

**Comment by gamer22026** [comment]
I'm using a namespace called `apisix` 
Adding serviceaccount `cmsnr` to the `apisix` namespace allowed the injector to work for a deployment called `apisix`, however the cmsnr-client container injected only runs `opa watch -d apisix ` and seems to be missing the `-n apisix` parameter causing it to use `default` namespace instead, leading to the error:

`E0207 23:28:55.731914       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.22.3/tools/cache/reflector.go:167: Failed to watch *v1alpha1.OpaPolicy: failed to list *v1alpha1.OpaPolicy: opapolicies.cmsnr.com is forbidden: User "system:serviceaccount:apisix:cmsnr" cannot list resource "opapolicies" in API group "cmsnr.com" in the namespace "default"`

**Comment by hooksie1** [comment]
Sorry for the delay, I'll be taking a look at this this week.

**Comment by hooksie1** [comment]
So the namespace not showing up in the deployment should be fixed. However the original thought for this was for shared clusters where a team controlled a namespace and their own policies. Some thought would need to be put in around having a cluster wide controller that handled OPA policies since the deployment names could collide between namespaces.
